const { query } = require('../config/database');

// CaseDetails Model with PostgreSQL integration
class CaseDetails {
  constructor(caseId, description, scNo, createdOn, createdBy, courtName, caseType, courtCity, courtState) {
    this.caseId = caseId;
    this.description = description;
    this.scNo = scNo;
    this.createdOn = createdOn || new Date();
    this.createdBy = createdBy || null;
    this.courtName = courtName || null;
    this.caseType = caseType || null;
    this.courtCity = courtCity || null;
    this.courtState = courtState || null;
  }

  // Convert to JSON
  toJSON() {
    return {
      caseId: this.caseId,
      description: this.description,
      scNo: this.scNo,
      createdOn: this.createdOn,
      createdBy: this.createdBy,
      courtName: this.courtName,
      caseType: this.caseType,
      courtCity: this.courtCity,
      courtState: this.courtState
    };
  }

  // Get all case details
  static async findAll() {
    // Use quoted table name to handle case sensitivity
    const result = await query(
      'SELECT * FROM "tblCaseDetails" ORDER BY created_on DESC'
    );
    
    console.log('findAll - Number of rows:', result.rows.length);
    if (result.rows.length > 0) {
      console.log('findAll - First row sample:', JSON.stringify(result.rows[0], null, 2));
    }
    
    return result.rows.map(row => {
      return new CaseDetails(
        row.case_id,
        row.description,
        row.sc_no,
        row.created_on,
        row.created_by,
        row.court_name,
        row.case_type,
        row.court_city,
        row.court_state
      );
    });
  }

  // Find case details by ID
  static async findById(caseId) {
    const result = await query(
      'SELECT * FROM "tblCaseDetails" WHERE case_id = $1',
      [caseId]
    );
    if (result.rows.length === 0) {
      return null;
    }
    const row = result.rows[0];
    return new CaseDetails(
      row.case_id,
      row.description,
      row.sc_no,
      row.created_on,
      row.created_by,
      row.court_name,
      row.case_type,
      row.court_city,
      row.court_state
    );
  }

  // Find case details by SC Number
  static async findByScNo(scNo) {
    const result = await query(
      'SELECT * FROM "tblCaseDetails" WHERE sc_no = $1',
      [scNo]
    );
    if (result.rows.length === 0) {
      return null;
    }
    const row = result.rows[0];
    return new CaseDetails(
      row.case_id,
      row.description,
      row.sc_no,
      row.created_on,
      row.created_by,
      row.court_name,
      row.case_type,
      row.court_city,
      row.court_state
    );
  }

  // Find case details by created_by
  static async findByCreatedBy(createdBy) {
    const result = await query(
      'SELECT * FROM "tblCaseDetails" WHERE created_by = $1 ORDER BY created_on DESC',
      [createdBy]
    );
    return result.rows.map(row => new CaseDetails(
      row.case_id,
      row.description,
      row.sc_no,
      row.created_on,
      row.created_by,
      row.court_name,
      row.case_type,
      row.court_city,
      row.court_state
    ));
  }

  // Create new case details
  // case_id will be auto-generated by database trigger as CASE001, CASE002, etc.
  static async create(description, scNo, createdBy, courtName, caseType, courtCity, courtState) {
    // Insert without case_id - trigger will auto-generate it
    const result = await query(
      'INSERT INTO "tblCaseDetails" (description, sc_no, created_by, court_name, case_type, court_city, court_state) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *',
      [description, scNo, createdBy, courtName, caseType, courtCity || null, courtState || null]
    );
    const row = result.rows[0];
    return new CaseDetails(
      row.case_id,
      row.description,
      row.sc_no,
      row.created_on,
      row.created_by,
      row.court_name,
      row.case_type,
      row.court_city,
      row.court_state
    );
  }

  // Update case details
  async update(description, scNo, createdBy, courtName, caseType, courtCity, courtState) {
    const updates = [];
    const values = [];
    let paramCount = 1;

    if (description !== undefined) {
      updates.push(`description = $${paramCount}`);
      values.push(description);
      paramCount++;
      this.description = description;
    }

    if (scNo !== undefined) {
      updates.push(`sc_no = $${paramCount}`);
      values.push(scNo);
      paramCount++;
      this.scNo = scNo;
    }

    if (createdBy !== undefined) {
      updates.push(`created_by = $${paramCount}`);
      values.push(createdBy);
      paramCount++;
      this.createdBy = createdBy;
    }

    if (courtName !== undefined) {
      updates.push(`court_name = $${paramCount}`);
      values.push(courtName);
      paramCount++;
      this.courtName = courtName;
    }

    if (caseType !== undefined) {
      updates.push(`case_type = $${paramCount}`);
      values.push(caseType);
      paramCount++;
      this.caseType = caseType;
    }

    if (courtCity !== undefined) {
      updates.push(`court_city = $${paramCount}`);
      values.push(courtCity);
      paramCount++;
      this.courtCity = courtCity;
    }

    if (courtState !== undefined) {
      updates.push(`court_state = $${paramCount}`);
      values.push(courtState);
      paramCount++;
      this.courtState = courtState;
    }

    if (updates.length === 0) {
      return this;
    }

    values.push(this.caseId);
    const result = await query(
      `UPDATE "tblCaseDetails" SET ${updates.join(', ')} WHERE case_id = $${paramCount} RETURNING *`,
      values
    );

    const row = result.rows[0];
    this.description = row.description;
    this.scNo = row.sc_no;
    this.createdBy = row.created_by;
    this.courtName = row.court_name;
    this.caseType = row.case_type;
    this.courtCity = row.court_city;
    this.courtState = row.court_state;
    return this;
  }

  // Delete case details
  async delete() {
    await query('DELETE FROM "tblCaseDetails" WHERE case_id = $1', [this.caseId]);
    return true;
  }
}

module.exports = CaseDetails;

